name: Unity Actions - Builder 😎

on: 
  push:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: 
          - ubuntu-latest
        projectPath: 
          - ./
        unityVersion: 
          - 2021.2.12f1
        targetPlatform: 
          - StandaloneLinux64
        # os: 
        #   - windows-2019
        # projectPath: 
        #   - ./
        # unityVersion: 
        #   - 2021.2.12f1
        # targetPlatform: 
        #   - StandaloneWindows64 # Build a Windows 64-bit standalone.
        # include:
        #   - os: ubuntu-latest
        #     targetPlatform: StandaloneLinux64 # Build a Linux 64-bit standalone.
        #     projectPath: ./
        #     unityVersion: 2021.2.12f1
        #   - os: macos-latest
        #     targetPlatform: StandaloneOSX # Build a MacOS 64-bit standalone.
        #     projectPath: ./
        #     unityVersion: 2021.2.12f1
          
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true

      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
            Library-

      - uses: game-ci/unity-builder@main
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          targetPlatform: ${{ matrix.targetPlatform }}
          
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

  release:
    needs: [build]
    name: "Create Github Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Build
      - name: Zip build
        run: |
          cd ../../Grief-Day/Grief-Day
          ls
          
          pushd StandaloneLinux64
          zip -r ../../StandaloneLinux64.zip .
          popd
          
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            
            StandaloneLinux64.zip
            